// Code generated by "stringer -type=ConstraintType"; DO NOT EDIT

package dbsql2go

import "fmt"

const _ConstraintType_name = "UnknownConstraintPKFKUnique"

var _ConstraintType_index = [...]uint8{0, 17, 19, 21, 27}

func (i ConstraintType) String() string {
	if i < 0 || i >= ConstraintType(len(_ConstraintType_index)-1) {
		return fmt.Sprintf("ConstraintType(%d)", i)
	}
	return _ConstraintType_name[_ConstraintType_index[i]:_ConstraintType_index[i+1]]
}
