// Code generated by "stringer -type=ConstraintType"; DO NOT EDIT

package dbsql2go

import "fmt"

const _ConstraintType_name = "PKFKUnique"

var _ConstraintType_index = [...]uint8{0, 2, 4, 10}

func (i ConstraintType) String() string {
	i -= 1
	if i < 0 || i >= ConstraintType(len(_ConstraintType_index)-1) {
		return fmt.Sprintf("ConstraintType(%d)", i+1)
	}
	return _ConstraintType_name[_ConstraintType_index[i]:_ConstraintType_index[i+1]]
}
