// Code generated by "stringer -type=DBType"; DO NOT EDIT

package dbsql2go

import "fmt"

const _DBType_name = "UnsupportedMySQL"

var _DBType_index = [...]uint8{0, 11, 16}

func (i DBType) String() string {
	if i < 0 || i >= DBType(len(_DBType_index)-1) {
		return fmt.Sprintf("DBType(%d)", i)
	}
	return _DBType_name[_DBType_index[i]:_DBType_index[i+1]]
}
