// Code generated by "stringer -type=IndexType"; DO NOT EDIT

package dbsql2go

import "fmt"

const _IndexType_name = "PrimaryKeyStandard"

var _IndexType_index = [...]uint8{0, 10, 18}

func (i IndexType) String() string {
	i -= 1
	if i < 0 || i >= IndexType(len(_IndexType_index)-1) {
		return fmt.Sprintf("IndexType(%d)", i+1)
	}
	return _IndexType_name[_IndexType_index[i]:_IndexType_index[i+1]]
}
